version: '3.8'

services:

  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  #php:
  # build:
  #   context: .
  #    dockerfile: dockerfiles/php.dockerfile
  # volumes:
  #    - ./src:/var/www/html:delegated

  php:
    image: laravel:7.4
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    mysql:
      image: mysql:5.7
      env_file:
        - ./env/mysql.env
      composer:
        image: composer:latest
        volumes:
          - ./src:/var/www/html
        entrypoint: ["composer", "--ignore-platform-reqs"]
      artisan:
        image: php:7.4-cli
        volumes:
          - ./src:/var/www/html
        entrypoint: ['php', '/var/www/html/artisan']
        depends_on:
          - php
          - mysql
      npm:
        image: node:14
        working_dir: /var/www/html
        entrypoint: ["npm"]
        volumes:
          - ./src:/var/www/html
